### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by JanVan01** [mdragunski/Geosoft2-WS14-15-Gruppe5#1]

**Comment by ummelmann** [comment]
I´m not ready yet, but this is my actual work...

Code-Review Daniel Ummelmann:

Reviewed Code: My-Meta-Maps by Group 
1.  I downloaded the source-code and identified the programming language as PHP. 
2.  I created a code-review-checklist for that language.
3.  I published the code-review-checklist on google-drive (available under https://drive.google.com/file/d/0B5M1pY-_8US0eU5wN0tiUFFYTzg/view?usp=sharing).
4.  The installation of the code without watching any documentation (installed apache-webserver on Ubuntu-Linux and installed the php-packages – controlled that php works by phpinfo) resulted in the following error:
   [Wed Dec 31 17:35:08.664841 2014] [:error] [pid 7247] [client 192.168.137.1:54060] PHP Fatal error:  require(): Failed opening required '/var/www/html/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/bootstrap/autoload.php on line 17
   Which points out, that the application (or better the bootstrap-framework) tries to import some libraries from directories or symlinks which are not available in this basic installation.
5.  After reading the installation-documentation I installed additional packages and controlled the versions to meet the requirements:
   Apache HTTPS >= 2.2 with mod_rewrite-> Apache/2.4.7 (Ubuntu) with mod_rewrite
   PostgreSQL >= 9.1 -> PostgreSQL 9.3.5
   PostGIS >= 2.0 -> 
   PHP with JSON MCrypt and other default PHP extensions >= 5.4 -> PHP/5.5.9-1ubuntu4.5
   Composer
   Started Composer, but the Composer-Script died with this message:
   [RuntimeException]
   Error Output: PHP Fatal error:  Class 'Lamb\LaravelPostgisDatabase\PostgisDatab
   aseServiceProvider' not found in /var/www/html/vendor/laravel/framework/src/Ill
   uminate/Foundation/ProviderRepository.php on line 157
6.  I installed PDT (PHP Development Tools) in Eclipse and imported the project for the review (worked).
7. 7.1   I understand, that bootstrap is needed for the application and that application itself is loaded by somehow by the artissian-framework, but I don´t unswrstand how this is done.
   7.2   Gone through my checklist (see attachment).
   7.3   Automatic code-analysis-tools have been applied to the code without any new informations.
8.  –Work in progress-
